name: lint

on: workflow_call

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️ ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: Get changed files
        if: github.event_name == 'pull_request'
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Setup Python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Run pre-commit 🚀
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: ${{ github.event_name == 'pull_request' && format('--files {0}', join(steps.changed-files.outputs.all_changed_files, ' ')) || '--all-files' }}
