name: lint

on: workflow_call

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install flake8 black pydocstyle
      - name: Check formatting with black
        if: always()
        run: |
          black --check $(git ls-files '*.py')
      - name: Analyzing the code with Flake8
        if: always()
        run: |
          flake8 $(git ls-files '*.py')
      - name: Analyzing the code with Pydocstyle
        if: always()
        run: |
          pydocstyle $(git ls-files '*.py')
