name: lint-bot

on: workflow_call

permissions:
  contents: write

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️ ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: Setup Python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies 📦
        run: |
          python -m pip install pre-commit

      - name: Run pre-commit 🚀
        run: |
          pre-commit run --all-files --show-diff-on-failure

      - name: Commit changes 📝
        if: failure()
        run: |
          git config --local user.email "ivydl.team@gmail.com"
          git config --local user.name "ivy-branch"
          git add .
          git commit -m "🤖 Lint code"
          git push
